import Head from 'next/head'
import { useState } from 'react'
import { FiMoon } from "react-icons/fi";
import { FiSun } from "react-icons/fi";

export default function Home() {

  const [Mode ,setMode] = useState(0)

  return (
    <>
      <Head>
        <title>Themes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={Mode ? 'dark' : ''}>
        <section className='bg-amber-50 min-h-screen px-10 lg:px-32 py-10 font-tileNeon dark:bg-neutral-800 transition-colors duration-200'>
          <nav className='flex justify-between items-center'>
            <h1 className='text-5xl font-gloock text-neutral-800 dark:text-amber-50'>
              <u>Sumit Mule</u>
              </h1>
            <ul>
              <li className='hover:scale-110 transition-all' onClick={() => setMode(!Mode)}>
                { Mode ? <FiMoon size={40} color='#f7f5f3'/> : <FiSun size={40}/>}
              </li>
            </ul>
          </nav>


          <div className='mt-40 text-neutral-800 dark:text-amber-50 '>
            <h1 className='text-3xl font-bold'>THIS IS A DEMO OF THEME CHANGER {Mode ? '😴' : '😀'}</h1>
            <p className='text-lg my-5'>It is built using Tailwind CSS and React Hooks. <tt><b>useState</b></tt>  is a Hook that lets you add React state to function components.
            <br/>
            <br/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus orci odio, vel maximus eros tincidunt ut. Nunc sodales enim sed ligula gravida consectetur. Vestibulum egestas risus sit amet nulla scelerisque, vel tempus risus feugiat. Sed vitae magna ipsum. Sed fringilla dictum tellus vitae convallis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent neque elit, dictum sed elit quis, vestibulum consectetur ipsum. Nam aliquet pharetra mi ac dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin sed odio sit amet diam porta pretium. Donec tincidunt eros in magna porta, id viverra urna pulvinar.
            </p>
            <a href='https://github.com/sumitmule/theme-changer' target={'_blank'} className='bg-neutral-800 mt-8 shadow-xl border-none p-3 hover:ring-4 ring-neutral-400 transition-all rounded-xl text-amber-50 dark:text-neutral-800 dark:bg-amber-50'>Source Code</a>
          </div>
        </section>
      </main>
    </>
  )
}
